-- MySQL Script generated by MySQL Workbench
-- Fri 03 Oct 2025 06:21:03 AM MSK
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ideadb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ideadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ideadb` DEFAULT CHARACTER SET utf8 ;
USE `ideadb` ;

-- -----------------------------------------------------
-- Table `ideadb`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ideadb`.`Category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` TINYTEXT NOT NULL,
  `parent_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `parent_id` (`parent_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ideadb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ideadb`.`Product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(1024) NOT NULL,
  `price` INT NOT NULL,
  `cat_id` INT NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Product_Category_idx` (`cat_id` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Category`
    FOREIGN KEY (`cat_id`)
    REFERENCES `ideadb`.`Category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ideadb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ideadb`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(512) NOT NULL,
  `address` VARCHAR(512) NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ideadb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ideadb`.`Order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `u_id` INT NOT NULL,
  `created` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Order_User1_idx` (`u_id` ASC) VISIBLE,
  CONSTRAINT `fk_Order_User1`
    FOREIGN KEY (`u_id`)
    REFERENCES `ideadb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ideadb`.`OrderItem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ideadb`.`OrderItem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ord_id` INT NOT NULL,
  `prod_id` INT NOT NULL,
  `count` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_OrderItem_Order1_idx` (`ord_id` ASC) VISIBLE,
  INDEX `fk_OrderItem_Product1_idx` (`prod_id` ASC) VISIBLE,
  CONSTRAINT `fk_OrderItem_Order1`
    FOREIGN KEY (`ord_id`)
    REFERENCES `ideadb`.`Order` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderItem_Product1`
    FOREIGN KEY (`prod_id`)
    REFERENCES `ideadb`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
